myapp:
  image: ehdwn1212/mazingfriends:latest
  command: npm start
  working_dir: /MazingFriends
  expose:
    - "3000"
  links:
    - db
  environment:
    SEQ_DB: postgres
    SEQ_USER: postgres
    SEQ_PW: kim0243
    DATABASE_URL: postgres://postgres:kim0243@192.168.99.100:5432/postgres
db:
  image: ehdwn1212/postgres:latest
  expose:
  - "5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: kim0243